<!DOCTYPE html>
<html lang="en">
<head>
    <title>NanoBeacom MP Tool Server</title>
	<style>
		body {
			margin: 0 auto; 
			justify-content: center;
			align-items: center;
			width:1000px
		}
	</style>
</head>
<body>
	%
	<h3 align="center">NanoBeacom MP Tool Http Server {{version}}</h3>
	% end
	<h4>Burn http post JSON @ http://host:port/burn/uart-com</h4>
	<h4>RAM Test http post JSON @ http://host:port/ram/uart-com</h4>
	<h6>uart-com is UART device Port. e.g. COM6</h6>
	<i>Json Param Description</i>
	<table border="5">
		<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Value Description</th>
		<th>Value e.g.</th>
		<th>Comment</th>
		</tr>
		<tr>
			<td>key0</td>
			<td>string</td>
			<td>key0 for cryption,16-byte hexadecimal</td>
			<td>000102030405060708090a0b0c0d0e0f</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>key1</td>
			<td>string</td>
			<td>key0 for cryption,16-byte hexadecimal</td>
			<td>000102030405060708090a0b0c0d0e0f</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>key2</td>
			<td>string</td>
			<td>key0 for cryption,16-byte hexadecimal</td>
			<td>000102030405060708090a0b0c0d0e0f</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>addr1</td>
			<td>string</td>
			<td>address of ADV SET#1,6-byte hexadecimal</td>
			<td>060504030201</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>addr2</td>
			<td>string</td>
			<td>address of ADV SET#2,6-byte hexadecimal</td>
			<td>060504030201</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>addr3</td>
			<td>string</td>
			<td>address of ADV SET#3,6-byte hexadecimal</td>
			<td>060504030201</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>cust_id</td>
			<td>string</td>
			<td>Customer Product ID,6-byte hexadecimal</td>
			<td>010203040506</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>debug</td>
			<td>int</td>
			<td>0 or 1; 1 generate packet file for debug</td>
			<td>1</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>reset_chip</td>
			<td>int</td>
			<td>0 or 1; 1 rest chip after burn</td>
			<td>1</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>magic</td>
			<td>int</td>
			<td>magic code, the response data will contain this field</td>
			<td></td>
			<td>optional</td>
		</tr>
		<tr>
			<td>cfg</td>
			<td>json</td>
			<td>Configuration data generated by NanoBeaconConfigTool</td>
			<td></td>
			<td>mandatory</td>
		</tr>
	</table>
	
	<div style="color:#00FF00">
		<p>&emsp;</p>
	</div>

	<h4>DTM Test http post JSON @ http://host:port/dtm/uart-com</h4>
	<h6>uart-com is UART device Port. e.g. COM6</h6>
	<i>Json Param Description</i>
	<table border="5">
		<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Value Description</th>
	
		<th>Comment</th>
		</tr>
		<tr>
			<td>start</td>
			<td>int</td>
			<td>0 or 1; 1 start DTM test; 0 stop DTM test</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>hw_ch</td>
			<td>int</td>
			<td>0 ~ 39; physical channel number, 0 is 2.402Ghz, 39 is 2.480Ghz</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>length</td>
			<td>int</td>
			<td>0 ~ 255; length of advertising data,</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>payload_pattern</td>
			<td>int</td>
			<td>0 ~ 7 (prbs9,0x0f,0x55,prbs15,0xff,0x0,0xf0,0xaa)</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>phy</td>
			<td>int</td>
			<td>1 or 3; 1 is 1M PHY; 3 is 125K coded PHY</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>infinite_cycle</td>
			<td>int</td>
			<td>0 or 1; 1 infinite cycle</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>tx_power</td>
			<td>int</td>
			<td>-54 ~ 4, dBm</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>pa_gain</td>
			<td>int</td>
			<td>0 ~ 120, Gain corresponding to TX power</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>cap_code</td>
			<td>int</td>
			<td>0 ~ 15, internal capacitor code</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>magic</td>
			<td>int</td>
			<td>magic code, the response data will contain this field</td>
			<td></td>
			<td>optional</td>
		</tr>
		
	</table>
	<div style="color:#00FF00">
		<p>&emsp;</p>
	</div>
	<h4>Carrier Test http post JSON @ http://host:port/carrier/uart-com</h4>
	<h6>uart-com is UART device Port. e.g. COM6</h6>
	<i>Json Param Description</i>
	<table border="5">
		<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Value Description</th>
		<th>Comment</th>
		</tr>
		<tr>
			<td>start</td>
			<td>int</td>
			<td>0 or 1; 1 start Carrier test; 0 stop Carrier test</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>hw_ch</td>
			<td>int</td>
			<td>0 ~ 39; physical channel number, 0 is 2.402Ghz, 39 is 2.480Ghz</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>tx_power</td>
			<td>int</td>
			<td>-54 ~ 4, dBm</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>pa_gain</td>
			<td>int</td>
			<td>0 ~ 120, Gain corresponding to TX power</td>
			<td>optional</td>
		</tr>
		<tr>
			<td>cap_code</td>
			<td>int</td>
			<td>0 ~ 15, internal capacitor code</td>
			<td>mandatory</td>
		</tr>
		<tr>
			<td>magic</td>
			<td>int</td>
			<td>magic code, the response data will contain this field</td>
			<td></td>
			<td>optional</td>
		</tr>
		
	</table>
	<div style="color:#00FF00">
		<p>&emsp;</p>
	</div>
	<h4>Json Response Description</h4>
	<table border="1">
		<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Value Description</th>
		</tr>
		<tr>
			<td>cmd</td>
			<td>string</td>
			<td>action (burn,ram,dtm,carrier)</td>
		</tr>
		<tr>
			<td>com</td>
			<td>string</td>
			<td>UART device Port</td>
		</tr>
		<tr>
			<td>ret</td>
			<td>int</td>
			<td>0 success, others failed</td>
		</tr>
		<tr>
			<td>msg</td>
			<td>string</td>
			<td>Description of the ret</td>
		</tr>
		<tr>
			<td>magic</td>
			<td></td>
			<td>magic code from request</td>
		</tr>
		<tr>
			<td>time</td>
			<td>int</td>
			<td>timestamp</td>
		</tr>
		
		
	</table>
	
	<div style="color:#00FF00">
		<p>&emsp;</p>
	</div>
	<h4>Modify the server IP and port</h4>
		<p style="text-indent:50px">open the settings.json file in the same directory and modify the mp_server field, and then restart</p>
			<p style="text-indent:80px">mp_server" : {</p>
				<p style="text-indent:110px"> "host" : "127.0.0.1",</p>
				<p style="text-indent:110px">"port" : 8080</p>
			<p style="text-indent:80px">}</p>
	
	<div style="color:#00FF00">
		<p>====================================================</p>
	</div>
	<h4>Version get @ http://host:port/version</h4>
	<i>Json Response Description</i>
	<table border="1">
		<tr>
		<th>Key</th>
		<th>Value Type</th>
		<th>Value Description</th>
		</tr>
		<tr>
			<td>cmd</td>
			<td>string</td>
			<td>version</td>
		</tr>
		<tr>
			<td>ret</td>
			<td>int</td>
			<td>0 success, others failed</td>
		</tr>
		<tr>
			<td>msg</td>
			<td>string</td>
			<td>version of MP tool</td>
		</tr>
		<tr>
			<td>time</td>
			<td>int</td>
			<td>timestamp</td>
		</tr>
		
	</table>
	<div style="color:#00FF00">
		<p>&emsp;</p>
	</div>
</body>
</html>
